name: CI
on: [push, pull_request] # Kích hoạt khi push hoặc PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests and Package
        run: mvn package # Chạy cả test và đóng gói .jar

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-jar-file
          path: target/*.jar # Lưu file .jar lạ